project_name: tdl
dist: .tdl/dist
env:
  - GO111MODULE=on
builds:
  - binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{ .ModulePath }}/global.Version={{ .Version }}
      - -X {{ .ModulePath }}/global.Commit={{ .ShortCommit }}
      - -X {{ .ModulePath }}/global.CommitDate={{ .CommitDate }}
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - format: binary
changelog:
  use: github
  sort: asc
  groups:
    - title: New Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: Others
      order: 4
release:
  draft: true
